### PR TITLE
micromasters zendesk theme

### PR DESCRIPTION
**Pull request by HamzaIbnFarooq**
#### Related Issue
Fixes https://github.com/mitodl/micromasters/issues/4734

#### What this PR does
It changes the theme according to micromasters requirements shown [Here](https://invis.io/HQZS3LCBPAD#/440821532_MM_Zendesk_Page)

#### How to test
Currently, the Micromasters do not have any Zendesk support center set up, so I have created a trial account to work on theming, which can be seen here ==> https://hamza-test0001.zendesk.com/hc/en-us

#### Disclaimer
The failing tests are supposed to be `disabled` (as they might not be used in our current flow) or `configured properly` in a separate PR.

### CODE REVIEW

**Comment by HamzaIbnFarooq** [comment]
@pdpinch can you please review the theme and, also add Arbisoft's team members in this repo, as I am unable to mention any of them here.

**Review by asadiqbal08 — APPROVED** [review]
Changes seems good to me beside the build failure and also better to get feedback over the design look & feel 👍

**Comment by HamzaIbnFarooq** [comment]
> Changes seems good to me beside the build failure

The build failure is irrelevant as i think it's used for continuous deployments.

**Comment by HamzaIbnFarooq** [comment]
@pdpinch can you please review?

**Comment by pdpinch** [comment]
Can you hide the "Recent Activity" section? I'm not sure how we did it, but it's hidden on the [xPRO help center](https://xpro.zendesk.com/hc/en-us).

**Comment by HamzaIbnFarooq** [comment]
> Can you hide the "Recent Activity" section?

We can remove that via the admin panel's theme customization:
image

**Comment by pdpinch** [comment]
Looks good to me. I think you should merge it. 

We'll deploy it to the ZenDesk account when the new home page is released -- which could be a couple of weeks.

**Pull request merged**
