### PR TITLE
Update theme header design

### PR DESCRIPTION
**Pull request by arslanashraf7**
## Description
Updates header design for the theme
Related to #12 

## Screenshots
**Desktop**
Screenshot 2021-04-12 at 6 05 49 PM

**Mobile**
Screenshot 2021-04-12 at 6 08 46 PM

## Testing instructions
- You can visit the live deployed theme [here](https://testmm.zendesk.com/hc/en-us).
- Making sure that the expected changes are reflected in the theme.

### CODE REVIEW

**Comment by arslanashraf7** [comment]
@briangrossman, Can you take a look at the screenshots and [test deployment](https://testmm.zendesk.com/hc/en-us) of the theme and let me know if that looks good to you or it might require any changes.

**Review by HamzaIbnFarooq — APPROVED** [review]
LG

**Comment by arslanashraf7** [comment]
@briangrossman, The PR is merged and it's good to be deployed on prod. If you could let me know once the theme is deployed and I would just smoke & A/B test it as well.

**Comment by briangrossman** [comment]
@arslanashraf7 
It's on prod now... looks good!
https://mitx-micromasters.zendesk.com/hc/en-us

**Pull request merged**
