### PR TITLE
Adding Micromasters matching footer

### PR DESCRIPTION
**Pull request by arslanashraf7**
## Description

This PR Adds footer that matches the footer we have on Micromaster's main website

## Related Tickets
#5 
#6 

Changes can be verified on a test Zendesk account [here](https://mmtestsupport.zendesk.com/hc/en-us).

## Screenshots
**Desktop Screenshot**
Screenshot 2021-02-22 at 2 29 32 PM

**Mobile Screenshot**
Screenshot 2021-02-22 at 2 29 45 PM

### CODE REVIEW

**Comment by arslanashraf7** [comment]
@briangrossman, The PR is ready for review, Can you please have a look at the screenshots in the description and the [test account](https://mmtestsupport.zendesk.com/hc/en-us) where these changes can be verified.

Please let me know if anything needs to be changed.

**Comment by briangrossman** [comment]
@arslanashraf7 This looks good. One minor thing: even though the Contact Us link is prominently featured, I think you should keep the Contact Us link in the footer for consistency. 

I shared it with Abdul as well. He's good with it.

**Comment by arslanashraf7** [comment]
@briangrossman I've added the `Contact Us` link in the footer as well, I've updated the screenshots and also deployed the theme on the test link provided in the description. Let me know if the theme would need more tweaks.

**Review by HamzaIbnFarooq — APPROVED** [review]
LGTM

**Comment by briangrossman** [comment]
LGTM2 (Looks good to me, too)

**Pull request merged**
